title: Pagina personale di Primo Buscemi
author: Primo Buscemi
email: primobuscemi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  …ogni uomo, ognuno di noi, per essere libero, per essere fedele alla propria dignità, deve essere sempre un eretico. (Leonardo Sciascia)



twitter_username: PrimoBuscemi
github_username:  primobuscemi

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
